name: recipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  
  # Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.0.3
  
  # Serialization
  json_annotation: ^4.9.0
  
  # For caching network images
  cached_network_image: ^3.3.1
  
  # Equatable for equality checking
  equatable: ^2.0.5

  # Shared Preferences for storing user preferences
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.8
  retrofit_generator: ^10.0.0
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.0

flutter:
  uses-material-design: true
